# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sitechop
email: sitechop@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web development blog featuring beginner to intermediate
  level guides and tutorials on Front End Development, Ruby on Rails, Ubuntu,
  and Shopify.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sitechop.com" # the base hostname & protocol for your site
twitter_username: itsrobbyk
github_username:  robbyklein
author: Robert Klein
# Build settings
markdown: kramdown
paginate: 6
paginate_path: "/page-:num/"
gems: [jekyll-paginate]

